### ISSUE TITLE
Reviews: фото, имена, и ссылки на профили пользователей

### ISSUE THREAD

**Issue by alexsimkovich** [Plumsail/plumsail-site#1]

**Comment by jusper-dk** [comment]
На текущем сайте в продуктах Workflow Actions Pack, Org Chart, HelpDesk, вставлен виджет с отзывами клиентов YotPo. Не все клиенты используют социальные профили для sign up в эту систему, пожтому у них нет ни фото, ни ссылки не к-либо профиль. 

Мы добавили скрипт-костыль, который патчит содержимое виджета и подставляет данные из статичного массива. Во вложении эти скрипты для каждой из перечисленных страниц:
[Org Chart.txt](https://github.com/Plumsail/plumsail-site/files/1460757/Org.Chart.txt)
[Workflow Actions Pack.txt](https://github.com/Plumsail/plumsail-site/files/1460758/Workflow.Actions.Pack.txt)
[Help Desk.txt](https://github.com/Plumsail/plumsail-site/files/1460759/Help.Desk.txt)

Надо повторить эту же функциональность на новом сайте. Проверить, что отызвы выводятся в правильных местах и для правильных продуктов. 

Виджет уже вставлен, надо только проверить, что он правильно настроен и добавить вот эти скриптики. Лучше их объединить в один, а данные перенести в json разделив по продуктам.

**Comment by alexsimkovich** [comment]
@jusper-dk ready

**Comment by jusper-dk** [comment]
Добавь плз стили для ссылок (Reviews и имя пользователя) в отзывах (основной цвет продукта): 
![image](https://user-images.githubusercontent.com/27721442/32701878-5f632cda-c7ee-11e7-8245-f379caf53527.png)

**Comment by alexsimkovich** [comment]
@jusper-dk Fixed
