### ISSUE TITLE
mouseOver issue

### ISSUE THREAD

**Issue by alexsimkovich** [Plumsail/plumsail-site#3]

**Comment by jusper-dk** [comment]
Если убрать курсор, то так:
![image](https://user-images.githubusercontent.com/27721442/32765847-5dc9ff0e-c91d-11e7-82b2-4e48519963f6.png)

Надо, чтобы активный пункт оставался и картинка подсвечивалась.

**Comment by jusper-dk** [comment]
Перестало раскрываться меню в сайдбаре, подозреваю, связано с этой задачкой

Пример:
http://new.plumsail.com/sharepoint-orgchart/docs/templating-syntax/#

**Comment by jusper-dk** [comment]
На второй картинке не перемещается линия при наведении:
![image](https://user-images.githubusercontent.com/27721442/32766273-45b781f0-c91f-11e7-9cc0-dcb0c8faef7e.png)
